manifest-version = 1

[component]
name = "Amazon Kinesis"
version = "1.1.0"

category = "data-collection"
subcategory = "warehouse"
documentation = "https://www.edgee.cloud/docs/components/data-collection/amazon-kinesis"
repository = "https://github.com/edgee-cloud/amazon-kinesis-component"
icon-path = "kinesis.png"
wit-version = "1.0.0"
language = "Rust"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud)
and [Amazon Kinesis](https://aws.amazon.com/kinesis/),
allowing you to collect and forward analytics events to your streaming pipelines. 

All Kinesis records contain a full JSON dump of the incoming event.
'''

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && mv ./target/wasm32-wasip2/release/amazon_kinesis_component.wasm ./kinesis.wasm"
output_path = "kinesis.wasm"


[component.settings.aws_access_key]
title = "Your AWS Access Key"
type = "string"
required = true
description = "It corresponds to aws_access_key_id in your credentials file."

[component.settings.aws_secret_key]
title = "Your AWS Secret Access Key"
type = "string"
required = true
description = "It corresponds to aws_secret_access_key in your credentials file."

[component.settings.aws_session_token]
title = "Your AWS Session Token (optional)"
type = "string"
description = "Useful for tests, not recommended in production because it's short-lived"

[component.settings.aws_region]
title = "Your AWS Region"
type = "string"
required = true
description = "The AWS region short name, such as us-east-1 or eu-west-1."

[component.settings.kinesis_stream]
title = "Your Kinesis Stream name (or ARN)"
type = "string"
required = true
description = "Either the stream name or full ARN. Make sure to avoid leading or ending spaces."

[component.settings.kinesis_partition]
title = "Your Kinesis partition key (optional)"
type = "string"
description = "If provided, it's used as partition key for all PutRecord calls."
